<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMdNVFa4\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMdNVFa4/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerMdNVFa4.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerMdNVFa4\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerMdNVFa4\App_KernelDevDebugContainer([
    'container.build_hash' => 'MdNVFa4',
    'container.build_id' => '98cd7ead',
    'container.build_time' => 1680361067,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMdNVFa4');
