<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTsTQjZw\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTsTQjZw/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerTsTQjZw.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerTsTQjZw\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerTsTQjZw\App_KernelDevDebugContainer([
    'container.build_hash' => 'TsTQjZw',
    'container.build_id' => '6fe09f7c',
    'container.build_time' => 1680802970,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTsTQjZw');
