<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFK3Sp4t\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFK3Sp4t/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerFK3Sp4t.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerFK3Sp4t\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerFK3Sp4t\App_KernelDevDebugContainer([
    'container.build_hash' => 'FK3Sp4t',
    'container.build_id' => 'f1831686',
    'container.build_time' => 1680362398,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFK3Sp4t');
