<?php

namespace ContainerPCW863d;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Mix71J4Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Mix71J4' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Mix71J4'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'counter' => ['privates', 'App\\Service\\WordCounter', 'getWordCounterService', true],
            'doctrine' => ['services', 'doctrine', 'getDoctrineService', false],
        ], [
            'counter' => 'App\\Service\\WordCounter',
            'doctrine' => '?',
        ]);
    }
}
