<?php

namespace ContainerTsTQjZw;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Ui9fwdgService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ui9fwdg' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ui9fwdg'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'articleRepository' => ['privates', 'App\\Repository\\ArticleRepository', 'getArticleRepositoryService', true],
            'counter' => ['privates', 'App\\Service\\WordCounter', 'getWordCounterService', true],
        ], [
            'articleRepository' => 'App\\Repository\\ArticleRepository',
            'counter' => 'App\\Service\\WordCounter',
        ]);
    }
}
